language: java

cache:
  directories:
  - $HOME/.m2

jdk:
  - openjdk16
  - openjdk15
  - openjdk11
  - openjdk8

script:
  - ./mvnw clean verify
  - ./mvnw clean verify -Dspring.version=$(./travis/get_latest_version.sh spring-core 5.2) -Dspring-batch.version=$(./travis/get_latest_version.sh batch/spring-batch-core 4.2)
  - ./mvnw clean verify -Dspring.version=$(./travis/get_latest_version.sh spring-core 5.1) -Dspring-batch.version=$(./travis/get_latest_version.sh batch/spring-batch-core 4.1)
