var DATA = [
      { id:0, label:"org.mybatis.spring", link:"org/mybatis/spring/package-summary.html", type:"package" },
      { id:1, label:"org.mybatis.spring.MyBatisExceptionTranslator", link:"org/mybatis/spring/MyBatisExceptionTranslator.html", type:"class" },
      { id:2, label:"org.mybatis.spring.MyBatisSystemException", link:"org/mybatis/spring/MyBatisSystemException.html", type:"class" },
      { id:3, label:"org.mybatis.spring.SqlSessionFactoryBean", link:"org/mybatis/spring/SqlSessionFactoryBean.html", type:"class" },
      { id:4, label:"org.mybatis.spring.SqlSessionHolder", link:"org/mybatis/spring/SqlSessionHolder.html", type:"class" },
      { id:5, label:"org.mybatis.spring.SqlSessionTemplate", link:"org/mybatis/spring/SqlSessionTemplate.html", type:"class" },
      { id:6, label:"org.mybatis.spring.SqlSessionUtils", link:"org/mybatis/spring/SqlSessionUtils.html", type:"class" },
      { id:7, label:"org.mybatis.spring.annotation", link:"org/mybatis/spring/annotation/package-summary.html", type:"package" },
      { id:8, label:"org.mybatis.spring.annotation.MapperScan", link:"org/mybatis/spring/annotation/MapperScan.html", type:"class" },
      { id:9, label:"org.mybatis.spring.annotation.MapperScannerRegistrar", link:"org/mybatis/spring/annotation/MapperScannerRegistrar.html", type:"class" },
      { id:10, label:"org.mybatis.spring.batch", link:"org/mybatis/spring/batch/package-summary.html", type:"package" },
      { id:11, label:"org.mybatis.spring.batch.MyBatisBatchItemWriter", link:"org/mybatis/spring/batch/MyBatisBatchItemWriter.html", type:"class" },
      { id:12, label:"org.mybatis.spring.batch.MyBatisCursorItemReader", link:"org/mybatis/spring/batch/MyBatisCursorItemReader.html", type:"class" },
      { id:13, label:"org.mybatis.spring.batch.MyBatisPagingItemReader", link:"org/mybatis/spring/batch/MyBatisPagingItemReader.html", type:"class" },
      { id:14, label:"org.mybatis.spring.config", link:"org/mybatis/spring/config/package-summary.html", type:"package" },
      { id:15, label:"org.mybatis.spring.config.MapperScannerBeanDefinitionParser", link:"org/mybatis/spring/config/MapperScannerBeanDefinitionParser.html", type:"class" },
      { id:16, label:"org.mybatis.spring.config.NamespaceHandler", link:"org/mybatis/spring/config/NamespaceHandler.html", type:"class" },
      { id:17, label:"org.mybatis.spring.mapper", link:"org/mybatis/spring/mapper/package-summary.html", type:"package" },
      { id:18, label:"org.mybatis.spring.mapper.ClassPathMapperScanner", link:"org/mybatis/spring/mapper/ClassPathMapperScanner.html", type:"class" },
      { id:19, label:"org.mybatis.spring.mapper.MapperFactoryBean", link:"org/mybatis/spring/mapper/MapperFactoryBean.html", type:"class" },
      { id:20, label:"org.mybatis.spring.mapper.MapperScannerConfigurer", link:"org/mybatis/spring/mapper/MapperScannerConfigurer.html", type:"class" },
      { id:21, label:"org.mybatis.spring.support", link:"org/mybatis/spring/support/package-summary.html", type:"package" },
      { id:22, label:"org.mybatis.spring.support.SqlSessionDaoSupport", link:"org/mybatis/spring/support/SqlSessionDaoSupport.html", type:"class" },
      { id:23, label:"org.mybatis.spring.transaction", link:"org/mybatis/spring/transaction/package-summary.html", type:"package" },
      { id:24, label:"org.mybatis.spring.transaction.SpringManagedTransaction", link:"org/mybatis/spring/transaction/SpringManagedTransaction.html", type:"class" },
      { id:25, label:"org.mybatis.spring.transaction.SpringManagedTransactionFactory", link:"org/mybatis/spring/transaction/SpringManagedTransactionFactory.html", type:"class" }

    ];
